### ISSUE TITLE
ChimeraWSL - Cant install - 2024

### ISSUE THREAD

**Issue by vinberg88** [tranzystorekk/ChimeraWSL#2]
Hi Friend.

I cant make ChimeraWSL to run under Windows 11 - How to i install Chimera.

Have tried normal ways and Chimera wont bot.

Regards,
Mattias

**Comment by tranzystorekk** [comment]
I'm going to need more info:

- what steps you performed
- what doesn't work (error text, screenshots etc.)
- your environment details (terminal, precise windows version (`Windows Settings -> System -> About`), the ChimeraWSL release you downloaded)

**Comment by vinberg88** [comment]
I make it work - Thanks.

What do i do next ? how do i setup user and sudo/hostname etc

Please help me Mate.

Regards,
Mattias Vinberg

**Comment by tranzystorekk** [comment]
Please refer to the [wsldl docs](https://wsldl-pg.github.io/docs/) and the [Chimera resources](https://chimera-linux.org/), this is beyond the scope of this project.
